[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[python]
disabled = true

[elixir]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[git_status]
stashed = ""
