#!/usr/bin/env bash
#
# set os x defaults

# keyboard: set a fast keyboard repeat rate
defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 10
defaults write -g ApplePressAndHoldEnabled -bool false
